### ISSUE TITLE
Paging fails.

### ISSUE THREAD

**Issue by Tombstone01** [rodrigogs/xvideos#8]
Hello,

First of all, I really appreciate this library, so thank you for your hard work.

There is an issue though, I have been exploring this library but it seems that paging does not really work. For example, paging through fresh videos returns the same page, but in the pagination object, it does say the page has changed to page 2 for instance, but the videos are the same. 

Could you provide some clarity.

Thank you.

**Comment by rodrigogs** [comment]
I'm gonna check it

**Comment by rodrigogs** [comment]
Fixed :)
